[versions]
# libraries
junit = "4.13.2"
opentest4j = "1.3.0"
hutool = "5.8.11"
jackson = "2.15.3"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.4"
kotlin = "2.1.20"
kover = "0.9.1"
qodana = "2025.1.1"
lombok = "9.1.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
opentest4j = { group = "org.opentest4j", name = "opentest4j", version.ref = "opentest4j" }
hutool = { group = "cn.hutool", name = "hutool-all", version.ref = "hutool" }
jackson = { group = "com.fasterxml.jackson.core", name = "jackson-databind", version.ref = "jackson" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
lombok = { id = "io.freefair.lombok", version.ref = "lombok" }